### ISSUE TITLE
Permanent Rules Overlay in VS Code Windows

### ISSUE THREAD

**Issue by Git-AD** [Force-Config-Control/.github#2]
Got the extention in VS Code, and managed to run it on my connected org flows, but I can't access the results. The Rules filter is always present on the right side; it doesn't actually get used to filter anything, and more importantly, covers the results so that they can't be clicked to see the issues with each flow.

Attaching a screenshot to show what it looks like. Tried every way I could think of to get rid of it or get to the 'Details' button that's covered up.

![Flow Scanner Image Output](https://github.com/Force-Config-Control/.github/assets/142528240/81d7f952-3dab-4c7c-b2b2-7ac8c25f327d)

**Comment by RubenHalman** [comment]
@Git-AD Im sorry, I missed this at the time. this is now resolved though
